export const sample_foods = [
  {
    id: 1,
    name: "Pizza",
    price: 10.99,
    cookTime: 30,
    origins: ["Italian", "Fast Food", "Cheese", "Tomato"],
    stars: 4.5,
    imageUrl:
      "https://www.laespanolaaceites.com/wp-content/uploads/2019/06/pizza-con-chorizo-jamon-y-queso-1080x671.jpg",
    favorite: true,
    tags: ["Italian", "Fast Food", "Cheese", "Tomato"],
  },
  {
    id: 2,
    name: "Sushi",
    price: 15.99,
    cookTime: 45,
    origins: ["Italian", "Fast Food", "Cheese", "Tomato"],
    stars: 4.8,
    imageUrl: "https://imag.bonviveur.com/sushi-casero.webp",
    favorite: true,
    tags: ["Japanese", "Seafood", "Rice", "Fish"],
  },
  {
    id: 3,
    name: "Burger",
    price: 8.99,
    cookTime: 20,
    origins: ["Italian", "Fast Food", "Cheese", "Tomato"],
    stars: 4.2,
    imageUrl: "https://imag.bonviveur.com/sushi-casero.webp",
    favorite: true,
    tags: ["American", "Fast Food", "Beef", "Bread"],
  },
  {
    id: 4,
    name: "Pasta",
    price: 12.99,
    cookTime: 25,
    origins: ["Italian", "Fast Food", "Cheese", "Tomato"],
    stars: 4.6,
    imageUrl: "https://imag.bonviveur.com/sushi-casero.webp",
    favorite: false,
    tags: ["Italian", "Noodles", "Tomato Sauce"],
  },
  {
    id: 5,
    name: "Tacos",
    price: 9.99,
    cookTime: 15,
    origins: ["Italian", "Fast Food", "Cheese", "Tomato"],
    stars: 4.7,
    imageUrl: "https://imag.bonviveur.com/sushi-casero.webpg",
    favorite: true,
    tags: ["Mexican", "Street Food", "Beef", "Corn Tortilla"],
  },
];

export const sample_tags = [
  { name: "Italian", count: 3 },
  { name: "Fast Food", count: 3 },
  { name: "Pizza", count: 2 },
];
